name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    #  Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore

    # Compilar la solución
    - name: Build
      run: dotnet build --no-restore --configuration Debug

    # Ejecutar pruebas unitarias
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
    
