name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build
      run: dotnet build --no-restore --configuration Debug
 
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # # The next steps is for publish and and into the workflow
    # - name: Publish
    #   run: dotnet publish -c Debug -o ./publish

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: published-api
    #     path: ./publish
  
  # # This job is for push the iamge project into Docker Hub. 
  # deploy:
  #   deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
    
  #     - name: Download published artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: published-api
  #         path: ./app

       
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

      
  #     - name: Build Docker image
  #       run: |
  #         docker build -t ${{ env.IMAGE_NAME }}:latest ./app

      
  #     - name: Push Docker image
  #       run: |
  #         docker push ${{ env.IMAGE_NAME }}:latest